package com.example.kyg730.vizio.Components;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARCONTENT".
*/
public class ARContentDao extends AbstractDao<ARContent, Long> {

    public static final String TABLENAME = "ARCONTENT";

    /**
     * Properties of entity ARContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property TargetPath = new Property(1, String.class, "TargetPath", false, "TARGET_PATH");
        public final static Property ModelPath = new Property(2, String.class, "ModelPath", false, "MODEL_PATH");
        public final static Property Book_Id = new Property(3, long.class, "Book_Id", false, "BOOK__ID");
    }

    private DaoSession daoSession;

    private Query<ARContent> book_ARContentListQuery;

    public ARContentDao(DaoConfig config) {
        super(config);
    }
    
    public ARContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARCONTENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"TARGET_PATH\" TEXT NOT NULL ," + // 1: TargetPath
                "\"MODEL_PATH\" TEXT NOT NULL ," + // 2: ModelPath
                "\"BOOK__ID\" INTEGER NOT NULL );"); // 3: Book_Id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARCONTENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ARContent entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getTargetPath());
        stmt.bindString(3, entity.getModelPath());
        stmt.bindLong(4, entity.getBook_Id());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ARContent entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getTargetPath());
        stmt.bindString(3, entity.getModelPath());
        stmt.bindLong(4, entity.getBook_Id());
    }

    @Override
    protected final void attachEntity(ARContent entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ARContent readEntity(Cursor cursor, int offset) {
        ARContent entity = new ARContent( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // TargetPath
            cursor.getString(offset + 2), // ModelPath
            cursor.getLong(offset + 3) // Book_Id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ARContent entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTargetPath(cursor.getString(offset + 1));
        entity.setModelPath(cursor.getString(offset + 2));
        entity.setBook_Id(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ARContent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ARContent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ARContent entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "aRContentList" to-many relationship of Book. */
    public List<ARContent> _queryBook_ARContentList(long Book_Id) {
        synchronized (this) {
            if (book_ARContentListQuery == null) {
                QueryBuilder<ARContent> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Book_Id.eq(null));
                book_ARContentListQuery = queryBuilder.build();
            }
        }
        Query<ARContent> query = book_ARContentListQuery.forCurrentThread();
        query.setParameter(0, Book_Id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBookDao().getAllColumns());
            builder.append(" FROM ARCONTENT T");
            builder.append(" LEFT JOIN BOOK T0 ON T.\"BOOK__ID\"=T0.\"BOOK__ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ARContent loadCurrentDeep(Cursor cursor, boolean lock) {
        ARContent entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Book book = loadCurrentOther(daoSession.getBookDao(), cursor, offset);
         if(book != null) {
            entity.setBook(book);
        }

        return entity;    
    }

    public ARContent loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ARContent> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ARContent> list = new ArrayList<ARContent>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ARContent> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ARContent> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
