package com.example.kyg730.vizio.Components;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.kyg730.vizio.Components.Book;
import com.example.kyg730.vizio.Components.ARContent;

import com.example.kyg730.vizio.Components.BookDao;
import com.example.kyg730.vizio.Components.ARContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig aRContentDaoConfig;

    private final BookDao bookDao;
    private final ARContentDao aRContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        aRContentDaoConfig = daoConfigMap.get(ARContentDao.class).clone();
        aRContentDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        aRContentDao = new ARContentDao(aRContentDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(ARContent.class, aRContentDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        aRContentDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public ARContentDao getARContentDao() {
        return aRContentDao;
    }

}
